#!/usr/bin/env bash

set -e

export -n CDPATH

if [ "$1" = "--debug" ]; then
  export ROCKET_DEBUG=1
  shift
fi

if [ -n "$ROCKET_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi


# ----------------------------  Main functions  --------------------------------


# Function to display a nice header
show_header() {
  echo
  echo
}


# Function to ...
resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}


# Function to ...
abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}


# ----------------------------  MAIN  ------------------------------------------


if [ -z "${ROCKET_HEADER}" ]; then
  show_header
else 
  export ROCKET_HEADER="1"
fi

if [ -z "${ROCKET_ROOT}" ]; then
  ROCKET_ROOT="${HOME}/.rocket-launch"
else
  ROCKET_ROOT="${ROCKET_ROOT%/}"
fi
export ROCKET_ROOT

if [ -z "${ROCKET_DIR}" ]; then
  ROCKET_DIR="$(pwd)"
else
  cd "$ROCKET_DIR" 2>/dev/null || {
    echo "rocket: cannot change working directory to \`$ROCKET_DIR'"
    exit 1
  } >&2
  ROCKET_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export ROCKET_DIR

shopt -s nullglob

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

shopt -u nullglob

command="$1"
if [[ "$2" = "--help"  || "$2" = "-h"  ]]; then
  rocket-help "$command" >&2
  exit 1
fi

case "$command" in
"" | "-h" | "--help" )
  echo -e "$(rocket-help)" >&2
  ;;
"-v" )
  exec rocket---version
  ;;
* )
  command_path="$(command -v "rocket-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "rocket: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
