homebrew_installed_packages:
  - git
  - ssh-copy-id

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - google-chrome
  - slack
  - readdle-spark
  - iterm2
  - microsoft-teams
  - 1passwords
  - 1password-cli

xcode_xip_location: "/Users/{{ ansible_user_id }}/Downloads/Xcode_14.2.xip"
xcode_major_version: 14