---
# tasks file for ddev

- debug:
    msg: "DDEV unter {{ ansible_system }} - {{ ansible_os_family }} installieren."

- name: Assert supported distribution
  ansible.builtin.assert:
    that:
      - "ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper', 'homebrew')"

- name: 'Install ({{ ansible_pkg_mgr }})'
  include_tasks: 'install-{{ ansible_pkg_mgr }}.yml'