---
# tasks file for ddev

- debug:
    msg: "DDEV unter {{ ansible_system }} - {{ ansible_os_family }} installieren."

- name: Include OS specific variables.
  include_vars: "{{ ansible_system }}.yml"

- name: Install OS specific applications
  include_tasks: "setup-{{ ansible_system }}.yml"
