---

- hosts: all

  roles:
    - ddev
    - geerlingguy.mac.homebrew
#  tasks:
    #- name: Collect host facts
#  hosts: all
#  gather_facts: yes
#  tasks:
#    - name: Display host facts
#      debug:
#        var: ansible_facts
