---

- name: '[darwin] Include Darwin-specific variables'
  ansible.builtin.include_vars: defaults/darwin.yml

- name: '[darwin] Install Darwin-specific applications with homebrew cask'
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_nested:
    - "{{ terminal_apps }}"
  register: result
  failed_when:
    - result.failed
    - "not 'Error: It seems there is already ' in result.msg"

#- name: '[darwin] Install Darwin-specific applications with homebrew cask'
#  ansible.builtin.include_role: lwalley.iterm2
