---

- name: "[main] Include {{ ansible_os_family }}-specific tasks"
  ansible.builtin.include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: "[main] Include tomereli.oh-my-zsh-p10k role"
  ansible.builtin.include_role: tomereli.oh-my-zsh-p10k
  vars:
    users:
      - username: "{{ ansible_user_id }}"
